import type { Metadata } from "next";
import { Geist, Poppins } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import NavBar from "./staticLayouts/NavBar";
import CartUI from "@/app/staticLayouts/CartUI";
import ContactTrigger from "./staticLayouts/ContactTrigger";

const geistSans = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${poppins.variable} text-[#292828] w-screen overflow-x-hidden`}
      >
        <Providers>
          <NavBar />
          {children}
          <CartUI />
          <ContactTrigger />
        </Providers>
      </body>
    </html>
  );
}
